"use client";

import React from "react";
import "./submittal-coversheet.css";

export type StampBox = {
  role: "GC" | "Architect" | "Engineer" | "Subcontractor";
  /** Optional rendered stamp content. Pass null/undefined for empty box. */
  content?: React.ReactNode;
};

export type SubmittalCoversheetProps = {
  // Branding
  gcLogoUrl?: string;
  gcName?: string;

  // Project block
  projectName: string;
  projectNumber: string;
  projectLocation: string;

  // Submittal block
  submittalDescription: string;
  specSectionTitle: string;
  specSectionNumber: string;
  submittalNumber: string;
  revisionNumber: string;
  dateSubmitted: string; // formatted MM/DD/YY
  submittalDueDate: string; // formatted MM/DD/YYYY
  criticalSubmittal?: boolean;
  submittalPartyRequired?: boolean;
  copyTo?: string;

  // Stamps (always 4: GC, Architect, Engineer, Subcontractor)
  stamps?: [StampBox, StampBox, StampBox, StampBox];

  // Footer
  page?: number;
  totalPages?: number;
  version?: string; // e.g. "1.0"
};

const Field = ({
  label,
  value,
  wide = false,
}: {
  label: string;
  value: string;
  wide?: boolean;
}) => (
  <div className={`tt-field ${wide ? "tt-field--wide" : ""}`}>
    <span className="tt-field__label">{label}</span>
    <span className="tt-field__value">{value}</span>
  </div>
);

const Checkbox = ({
  label,
  checked,
}: {
  label: string;
  checked?: boolean;
}) => (
  <div className="tt-checkbox">
    <span className={`tt-checkbox__box ${checked ? "is-checked" : ""}`} />
    <span className="tt-checkbox__label">{label}</span>
  </div>
);

const StampCell = ({ stamp }: { stamp: StampBox }) => (
  <div className="tt-stamp" data-role={stamp.role}>
    {stamp.content ? (
      stamp.content
    ) : (
      <span className="tt-stamp__placeholder">
        {stamp.role} Stamp
      </span>
    )}
  </div>
);

export default function SubmittalCoversheet({
  gcLogoUrl,
  gcName,
  projectName,
  projectNumber,
  projectLocation,
  submittalDescription,
  specSectionTitle,
  specSectionNumber,
  submittalNumber,
  revisionNumber,
  dateSubmitted,
  submittalDueDate,
  criticalSubmittal = false,
  submittalPartyRequired = false,
  copyTo = "",
  stamps,
  page = 1,
  totalPages = 1,
  version = "1.0",
}: SubmittalCoversheetProps) {
  const defaultStamps: [StampBox, StampBox, StampBox, StampBox] = [
    { role: "GC" },
    { role: "Architect" },
    { role: "Engineer" },
    { role: "Subcontractor" },
  ];
  const resolvedStamps = stamps ?? defaultStamps;

  return (
    <article className="tt-coversheet" role="document">
      {/* Header */}
      <header className="tt-header">
        <h1 className="tt-title">Submittal Coversheet</h1>
        <div className="tt-brand">
          {gcLogoUrl ? (
            <img
              src={gcLogoUrl}
              alt={gcName ?? "General Contractor"}
              className="tt-brand__logo"
            />
          ) : (
            <span className="tt-brand__name">{gcName ?? ""}</span>
          )}
        </div>
      </header>

      {/* Project block */}
      <section className="tt-block tt-block--project">
        <Field label="Project Name" value={projectName} wide />
        <Field label="Project Number" value={projectNumber} wide />
        <Field label="Project Location" value={projectLocation} wide />
      </section>

      {/* Submittal block */}
      <section className="tt-block tt-block--submittal">
        <Field label="Submittal Description" value={submittalDescription} wide />
        <Field label="Spec Section Title" value={specSectionTitle} wide />

        <div className="tt-row">
          <Field label="Spec Section No." value={specSectionNumber} />
          <Field label="Submittal No." value={submittalNumber} />
          <Field label="Revision No." value={revisionNumber} />
        </div>

        <div className="tt-row">
          <Field label="Date Submitted" value={dateSubmitted} />
          <Field label="Submittal Due Date" value={submittalDueDate} />
        </div>

        <div className="tt-row tt-row--checks">
          <Checkbox label="Critical Submittal" checked={criticalSubmittal} />
          <Checkbox
            label="Submittal Party Required"
            checked={submittalPartyRequired}
          />
        </div>

        <Field label="Copy To" value={copyTo} wide />
      </section>

      {/* Stamp grid */}
      <section className="tt-stamps" aria-label="Review stamps">
        {resolvedStamps.map((s, i) => (
          <StampCell key={`${s.role}-${i}`} stamp={s} />
        ))}
      </section>

      {/* Footer */}
      <footer className="tt-footer">
        <span className="tt-footer__generated">
          Generated by TuttoHQ
        </span>
        <span className="tt-footer__page">
          {page} / {totalPages}
        </span>
        <span className="tt-footer__version">v. {version}</span>
      </footer>
    </article>
  );
}
