import type { SubmittalCoversheetProps, StampBox } from "@/components/submittals/SubmittalCoversheet"

function esc(s: string | undefined | null): string {
  return (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}

function field(label: string, value: string, wide = false): string {
  return `<div class="tt-field${wide ? " tt-field--wide" : ""}">
    <span class="tt-field__label">${esc(label)}</span>
    <span class="tt-field__value">${esc(value)}</span>
  </div>`
}

function checkbox(label: string, checked: boolean): string {
  return `<div class="tt-checkbox">
    <span class="tt-checkbox__box${checked ? " is-checked" : ""}"></span>
    <span class="tt-checkbox__label">${esc(label)}</span>
  </div>`
}

function stampCell(stamp: StampBox): string {
  const content = stamp.content
    ? `<div style="font-size:8.5pt;line-height:1.35">${esc(String(stamp.content))}</div>`
    : `<span class="tt-stamp__placeholder">${esc(stamp.role)} Stamp</span>`
  return `<div class="tt-stamp" data-role="${esc(stamp.role)}">${content}</div>`
}

export function buildCoversheetHtml(props: SubmittalCoversheetProps): string {
  const {
    gcLogoUrl, gcName,
    projectName, projectNumber, projectLocation,
    submittalDescription, specSectionTitle, specSectionNumber,
    submittalNumber, revisionNumber, dateSubmitted, submittalDueDate,
    criticalSubmittal = false, submittalPartyRequired = false, copyTo = "",
    stamps, page = 1, totalPages = 1, version = "1.0",
  } = props

  const resolvedStamps: [StampBox, StampBox, StampBox, StampBox] = stamps ?? [
    { role: "GC" }, { role: "Architect" }, { role: "Engineer" }, { role: "Subcontractor" },
  ]

  const brand = gcLogoUrl
    ? `<img src="${esc(gcLogoUrl)}" alt="${esc(gcName ?? "General Contractor")}" class="tt-brand__logo" />`
    : `<span class="tt-brand__name">${esc(gcName ?? "")}</span>`

  return `<article class="tt-coversheet" role="document">
  <header class="tt-header">
    <h1 class="tt-title">Submittal Coversheet</h1>
    <div class="tt-brand">${brand}</div>
  </header>

  <section class="tt-block tt-block--project">
    ${field("Project Name",     projectName,     true)}
    ${field("Project Number",   projectNumber,   true)}
    ${field("Project Location", projectLocation, true)}
  </section>

  <section class="tt-block tt-block--submittal">
    ${field("Submittal Description", submittalDescription, true)}
    ${field("Spec Section Title",    specSectionTitle,    true)}
    <div class="tt-row">
      ${field("Spec Section No.", specSectionNumber)}
      ${field("Submittal No.",    submittalNumber)}
      ${field("Revision No.",     revisionNumber)}
    </div>
    <div class="tt-row">
      ${field("Date Submitted",    dateSubmitted)}
      ${field("Submittal Due Date", submittalDueDate)}
    </div>
    <div class="tt-row tt-row--checks">
      ${checkbox("Critical Submittal",        criticalSubmittal)}
      ${checkbox("Submittal Party Required",  submittalPartyRequired)}
    </div>
    ${field("Copy To", copyTo, true)}
  </section>

  <section class="tt-stamps" aria-label="Review stamps">
    ${resolvedStamps.map(stampCell).join("\n    ")}
  </section>

  <footer class="tt-footer">
    <span class="tt-footer__generated">Generated by TuttoHQ</span>
    <span class="tt-footer__page">${page} / ${totalPages}</span>
    <span class="tt-footer__version">v. ${esc(version)}</span>
  </footer>
</article>`
}
