// Shared helpers for classifying Supabase Storage object paths in the
// `submittals` bucket. Pulled out into one module so multiple display
// surfaces (Library tree, search results, division counts) can't drift
// apart with subtly-different inline checks.
//
// Path shapes that matter here, all written by `${companyId}/...` prefix
// constructors in the API routes (post 2026-05-29 tenant-isolation refactor):
//
//   {company_id}/uploads/{uuid}_{name}.pdf              ← presigned upload
//   {company_id}/project-submittals/{project_id}/...    ← /api/generate-cover
//   {company_id}/transmittals/{submittal_id}/...        ← /api/transmittal/[id]
//   {company_id}/gmail-intake/{date}/{...}              ← gmail-intake
//   {company_id}/{rfis|punch|drawings|daily-reports|change-orders|closeout|submittal-packages|closeout-packages}/{...}
//
// The first segment is always a tenant identifier (currently a UUID, but
// the checks here treat it as opaque — survives future tenant-id changes).

/**
 * True when `path` points at a cover-sheet transmittal copy generated by
 * /api/generate-cover for a specific project.
 *
 * Pattern-match against the SECOND path segment so the tenant identifier
 * in the first segment is treated as a wildcard. Returns false for
 * null/undefined/empty and for paths that don't have at least three
 * segments (a real file lives under {tenant}/project-submittals/{project_id}/…).
 *
 * Used to HIDE transmittal copies from the cross-project Library views
 * (file lists, search results, per-section file counts). The copies stay
 * fully present and accessible inside their owning project's Submittal
 * Log — this helper does not affect access, only display filtering.
 */
export function isProjectTransmittalCopy(path: string | null | undefined): boolean {
  if (!path) return false
  const segments = path.split("/")
  return segments.length >= 3 && segments[1] === "project-submittals"
}
