import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

// POST /api/spec-books/finalize — confirms a direct-to-storage spec book upload
// landed, then records the real byte size.
//
// Parsing is deliberately NOT kicked off here: the Spec Books module triggers
// /parse while the scope wizard triggers /toc first (parsing before scope is
// set would AI-classify the whole book and ignore the scope filter). Each
// frontend caller owns its own next step.
export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const body = await req.json().catch(() => null)
  const documentId = typeof body?.document_id === "string" ? body.document_id.trim() : ""
  if (!documentId) return NextResponse.json({ error: "document_id is required" }, { status: 400 })

  const { data: doc, error: docError } = await supabase
    .from("project_documents")
    .select("id, file_path")
    .eq("id", documentId)
    .single()
  if (docError || !doc?.file_path) {
    return NextResponse.json({ error: "Document not found" }, { status: 404 })
  }

  // Defense-in-depth: the file_path was server-generated by the presigned-url
  // route (prepends {company_id}/), and RLS scoped the lookup above to the
  // caller's company. But validate the prefix anyway — catches any future
  // tampering or stale row state where finalize would otherwise touch a path
  // the caller can't actually reach under the new storage RLS.
  const { data: companyId } = await supabase.rpc("get_my_company_id")
  if (!companyId) {
    return NextResponse.json({ error: "No company association" }, { status: 500 })
  }
  if (!doc.file_path.startsWith(`${companyId}/`)) {
    return NextResponse.json({ error: "Document path is not tenant-scoped" }, { status: 400 })
  }

  // Verify the object actually landed at the expected path.
  const slash    = doc.file_path.lastIndexOf("/")
  const folder   = doc.file_path.slice(0, slash)
  const baseName = doc.file_path.slice(slash + 1)

  const { data: listed, error: listError } = await supabase.storage
    .from("submittals")
    .list(folder, { search: baseName, limit: 100 })
  if (listError) {
    return NextResponse.json({ error: listError.message }, { status: 500 })
  }

  const object = (listed ?? []).find(o => o.name === baseName)
  if (!object) {
    return NextResponse.json(
      { error: "The upload did not complete — no file was found in storage." },
      { status: 400 },
    )
  }

  const fileSize = (object.metadata?.size as number | undefined) ?? null

  const { data: updated, error: updateError } = await supabase
    .from("project_documents")
    .update({ file_size_bytes: fileSize })
    .eq("id", documentId)
    .select()
    .single()
  if (updateError) {
    return NextResponse.json({ error: updateError.message }, { status: 500 })
  }

  return NextResponse.json({ ok: true, document: updated })
}
