import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Privacy Policy — TuttoHQ",
  description:
    "How TuttoHQ collects, uses, and protects the information of general contractors using our construction document-management software.",
}

// Static marketing/legal page. Server component — no "use client", no data
// fetching. Sets its own dark full-height background because the global body
// background (globals.css / layout) is the light app theme.
export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#060b18] text-[#8b9ab5] antialiased">
      <div className="mx-auto max-w-3xl px-6 py-16 sm:py-24">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-[#7B9BB5] transition-colors hover:text-[#a9c0d6]"
        >
          <span aria-hidden="true">←</span> Back to home
        </Link>

        <h1 className="mt-10 text-3xl font-semibold tracking-tight text-[#f0f4ff] sm:text-4xl">
          Privacy Policy
        </h1>
        <p className="mt-3 text-sm text-[#6b7a95]">Last updated: July 2026</p>

        <p className="mt-8 text-[15px] leading-7">
          TuttoHQ (&ldquo;we&rdquo;, &ldquo;us&rdquo;) provides construction
          document-management software for general contractors. This policy
          explains what we collect, why, and your choices. Questions:{" "}
          <a
            href="mailto:privacy@tuttohq.com"
            className="text-[#7B9BB5] transition-colors hover:text-[#a9c0d6]"
          >
            privacy@tuttohq.com
          </a>
          .
        </p>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">
            Information we collect
          </h2>
          <ul className="mt-4 list-disc space-y-3 pl-5 text-[15px] leading-7 marker:text-[#7B9BB5]">
            <li>
              Account information: your name, email address, company name, and
              password (passwords are stored hashed, never in plain text).
            </li>
            <li>
              Content you upload: the construction documents, submittals,
              drawings, photos, project data, and related files you add to your
              account. This content belongs to you.
            </li>
            <li>
              Usage information necessary to operate the service: authentication
              timestamps and basic technical logs generated by our hosting
              providers.
            </li>
          </ul>
          <p className="mt-4 text-[15px] leading-7">
            We do not run third-party advertising or analytics trackers on the
            application. We do not sell your personal information.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">
            How we use information
          </h2>
          <p className="mt-4 text-[15px] leading-7">
            We use your information solely to provide and operate the service:
            authenticating your account, storing and organizing the documents
            you upload, generating the outputs you request (such as PDFs and
            reports), and maintaining the security and reliability of the
            platform.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">
            How information is stored and protected
          </h2>
          <p className="mt-4 text-[15px] leading-7">
            Your data is stored using Supabase (database, authentication, and
            file storage) and served via Vercel. Files are held in
            access-controlled storage, and database access is governed by
            row-level security so that each company&rsquo;s data is isolated to
            that company. We use industry-standard measures to protect your
            information, though no method of transmission or storage is
            completely secure.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">AI processing</h2>
          <p className="mt-4 text-[15px] leading-7">
            Some features (such as classifying a submittal by CSI division or
            extracting information from a document) process the content of files
            you upload using a third-party AI provider (Anthropic&rsquo;s Claude)
            to generate the result you requested. This processing is performed to
            deliver the feature; the content is sent for the purpose of producing
            your output.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">Sharing</h2>
          <p className="mt-4 text-[15px] leading-7">
            We share information only with the service providers that operate the
            platform on our behalf (such as our hosting, database, and AI
            processing providers), and only as needed to run the service. We may
            disclose information if required by law. We do not sell your data.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">
            Your choices and rights
          </h2>
          <p className="mt-4 text-[15px] leading-7">
            You may access, correct, or delete your account information, and you
            may request deletion of your account and associated data by
            contacting{" "}
            <a
              href="mailto:privacy@tuttohq.com"
              className="text-[#7B9BB5] transition-colors hover:text-[#a9c0d6]"
            >
              privacy@tuttohq.com
            </a>
            . Depending on where you live, you may have additional rights over
            your personal information.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">Data retention</h2>
          <p className="mt-4 text-[15px] leading-7">
            We retain your information for as long as your account is active or as
            needed to provide the service, and as required to comply with our
            legal obligations.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">
            Changes to this policy
          </h2>
          <p className="mt-4 text-[15px] leading-7">
            We may update this policy from time to time. Material changes will be
            reflected by the &ldquo;Last updated&rdquo; date above.
          </p>
        </section>

        <section className="mt-12">
          <h2 className="text-xl font-semibold text-[#f0f4ff]">Contact</h2>
          <p className="mt-4 text-[15px] leading-7">
            Questions about this policy:{" "}
            <a
              href="mailto:privacy@tuttohq.com"
              className="text-[#7B9BB5] transition-colors hover:text-[#a9c0d6]"
            >
              privacy@tuttohq.com
            </a>
          </p>
        </section>
      </div>
    </main>
  )
}
